branches:
  only:
  - source

language: node_js

sudo: false

node_js:
- '0.12'

before_install:
- openssl aes-256-cbc -K $encrypted_26b4962af0e7_key -iv $encrypted_26b4962af0e7_iv
  -in .travis/id_rsa_evatlsong.enc -out ~/.ssh/id_rsa_evatlsong -d
- chmod 600 ~/.ssh/id_rsa_evatlsong
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa_evatlsong
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "evatlsong"
- git config --global user.email evatlsong@gmail.com
- git clone -b master git@github.com:evatlsong/evatlsong.github.io.git .deploy_git

install:
- npm install hexo-cli -g
- npm install

script:
- hexo clean
- hexo g
- hexo d
